import path from 'node:path';

import { getAdapter } from '../registry/adapters.js';
import { getComponentEntry } from '../registry/components.js';
import { writeTextFile } from '../utils/fs.js';
import type { ConfigPaths, CliConfig } from '../config/project-config.js';

function createFileHeader(): string[] {
  return ['/* This file is auto-generated by @proto.ui/cli. */', '/* Do not edit by hand. */', ''];
}

function groupImports(componentIds: string[]): Map<string, Set<string>> {
  const packages = new Map<string, Set<string>>();

  for (const componentId of componentIds) {
    const entry = getComponentEntry(componentId);
    if (!entry) continue;
    const set = packages.get(entry.packageName) ?? new Set<string>();
    for (const item of entry.items) set.add(item.prototypeImport);
    packages.set(entry.packageName, set);
  }

  return packages;
}

export function renderHostIndex(host: string, componentIds: string[]): string {
  const adapter = getAdapter(host);
  if (!adapter) throw new Error(`unsupported host "${host}"`);

  const lines = createFileHeader();
  if (componentIds.length === 0) {
    lines.push('export {};', '');
    return lines.join('\n');
  }

  lines.push(adapter.createImport);
  if (adapter.runtimeImport) lines.push(adapter.runtimeImport);

  const grouped = groupImports(componentIds);
  for (const [packageName, imports] of grouped) {
    lines.push(`import { ${Array.from(imports).sort().join(', ')} } from '${packageName}';`);
  }

  lines.push('');
  if (adapter.adapterStatement) {
    lines.push(adapter.adapterStatement);
    lines.push('');
  }

  for (const componentId of componentIds) {
    const entry = getComponentEntry(componentId);
    if (!entry) continue;

    for (const item of entry.items) {
      if (host === 'react') {
        lines.push(`export const ${item.reactExport} = adapt(${item.prototypeImport});`);
      } else if (host === 'vue') {
        lines.push(`export const ${item.vueExport} = adapt(${item.prototypeImport});`);
      } else if (host === 'wc') {
        lines.push(
          `export const ${item.wcExport} = AdaptToWebComponent(${item.prototypeImport}, { registerAs: '${item.elementName}' });`
        );
      }
    }
    lines.push('');
  }

  return lines.join('\n').trimEnd() + '\n';
}

export function renderRootIndex(componentsByHost: Record<string, string[]>): string {
  const lines = createFileHeader();
  let wrote = false;

  for (const host of Object.keys(componentsByHost).sort()) {
    const adapter = getAdapter(host);
    const componentIds = componentsByHost[host] ?? [];

    for (const componentId of componentIds) {
      const entry = getComponentEntry(componentId);
      if (!entry) continue;

      for (const item of entry.items) {
        if (host === 'wc') {
          lines.push(`export { ${item.wcExport} } from './wc';`);
          wrote = true;
          continue;
        }

        const exportName = host === 'react' ? item.reactExport : item.vueExport;
        lines.push(
          `export { ${exportName} as ${adapter?.rootAliasPrefix}${exportName} } from './${host}';`
        );
        wrote = true;
      }
    }
  }

  if (!wrote) lines.push('export {};');
  lines.push('');
  return lines.join('\n');
}

export async function writeGeneratedIndexes(paths: ConfigPaths, config: CliConfig): Promise<void> {
  const componentsByHost = config.components ?? {};
  for (const host of Object.keys(componentsByHost)) {
    const componentIds = componentsByHost[host] ?? [];
    const hostFile = path.join(paths.componentsDir, host, 'index.ts');
    await writeTextFile(hostFile, renderHostIndex(host, componentIds));
  }

  await writeTextFile(
    path.join(paths.componentsDir, 'index.ts'),
    renderRootIndex(componentsByHost)
  );
}
