const PUI_STYLE_ATTR = 'data-pui-style';

type CssRule = {
  token: string;
  css: string[];
};

const spacing: Record<string, string> = {
  '0': '0px',
  '0.5': '0.125rem',
  '1': '0.25rem',
  '1.5': '0.375rem',
  '2': '0.5rem',
  '2.5': '0.625rem',
  '3': '0.75rem',
  '4': '1rem',
  '5': '1.25rem',
  '6': '1.5rem',
  '7': '1.75rem',
  '8': '2rem',
  '9': '2.25rem',
  '10': '2.5rem',
  '11': '2.75rem',
  '28': '7rem',
  '56': '14rem',
  '80': '20rem',
};

const colorVars = new Set([
  'accent',
  'accent-foreground',
  'background',
  'border',
  'destructive',
  'destructive-foreground',
  'foreground',
  'input',
  'muted',
  'muted-foreground',
  'primary',
  'primary-foreground',
  'ring',
  'secondary',
  'secondary-foreground',
]);

const staticUtilities: Record<string, string[]> = {
  absolute: ['position: absolute;'],
  fixed: ['position: fixed;'],
  relative: ['position: relative;'],
  block: ['display: block;'],
  flex: ['display: flex;'],
  'inline-flex': ['display: inline-flex;'],
  grid: ['display: grid;'],
  hidden: ['display: none;'],
  'flex-col': ['flex-direction: column;'],
  'items-center': ['align-items: center;'],
  'items-start': ['align-items: flex-start;'],
  'justify-center': ['justify-content: center;'],
  'shrink-0': ['flex-shrink: 0;'],
  'pointer-events-none': ['pointer-events: none;'],
  'cursor-default': ['cursor: default;'],
  'select-none': ['user-select: none;'],
  'outline-none': ['outline: 2px solid transparent;', 'outline-offset: 2px;'],
  'overflow-hidden': ['overflow: hidden;'],
  'whitespace-nowrap': ['white-space: nowrap;'],
  'bg-clip-padding': ['background-clip: padding-box;'],
  'will-change-transform': ['will-change: transform;'],
  'transition-all': ['transition-property: all;'],
  'transition-colors': [
    'transition-property: color, background-color, border-color, text-decoration-color, fill, stroke;',
  ],
  'duration-200': ['transition-duration: 200ms;'],
  'ease-in-out': ['transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);'],
  'font-medium': ['font-weight: 500;'],
  'font-semibold': ['font-weight: 600;'],
  'leading-6': ['line-height: 1.5rem;'],
  'leading-none': ['line-height: 1;'],
  'tracking-tight': ['letter-spacing: -0.025em;'],
  'text-left': ['text-align: left;'],
  'text-sm': ['font-size: 0.875rem;', 'line-height: 1.25rem;'],
  'text-lg': ['font-size: 1.125rem;', 'line-height: 1.75rem;'],
  'text-[0.8rem]': ['font-size: 0.8rem;'],
  underline: ['text-decoration-line: underline;'],
  'underline-offset-4': ['text-underline-offset: 4px;'],
  border: ['border-width: 1px;', 'border-style: solid;'],
  'border-transparent': ['border-color: transparent;'],
  'bg-transparent': ['background-color: transparent;'],
  'inset-0': ['inset: 0px;'],
  'opacity-50': ['opacity: 0.5;'],
  'ring-inset': ['--pui-ring-inset: inset;'],
  'ring-0': ['--pui-ring-width: 0px;', ringShadow()],
  'ring-2': ['--pui-ring-width: 2px;', ringShadow()],
  'ring-3': ['--pui-ring-width: 3px;', ringShadow()],
  'ring-offset-2': ['--pui-ring-offset-width: 2px;'],
  'ring-offset-background': ['--pui-ring-offset-color: var(--pui-background);'],
  'shadow-xs': ['box-shadow: 0 1px 2px 0 rgb(0 0 0 / 0.05);'],
  'shadow-lg': ['box-shadow: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1);'],
  'backdrop-blur-xs': ['backdrop-filter: blur(4px);'],
  'z-40': ['z-index: 40;'],
  'z-50': ['z-index: 50;'],
  'max-w-lg': ['max-width: 32rem;'],
  peer: [],
  'group/button': [],
  'group/toggle': [],
};

export function renderProtoStyleTokenCss(tokens: string[]): string {
  const rules: CssRule[] = [];
  const unknown: string[] = [];

  for (const token of tokens) {
    const rule = renderTokenRule(token);
    if (rule) rules.push(rule);
    else unknown.push(token);
  }

  const lines = [
    '/* This file is auto-generated by @proto.ui/cli (proto-ui tokens). */',
    '/* Do not edit by hand. */',
    '',
    '@layer proto-ui {',
  ];

  for (const rule of rules) {
    const selectors = buildSelectors(rule.token);
    if (selectors.length === 0 || rule.css.length === 0) continue;
    lines.push(`  ${selectors.join(',\n  ')} {`);
    for (const decl of rule.css) lines.push(`    ${decl}`);
    lines.push('  }');
    lines.push('');
  }

  if (unknown.length > 0) {
    lines.push('  /* Unsupported Proto UI style tokens:');
    for (const token of unknown) lines.push(`   * - ${token}`);
    lines.push('   */');
    lines.push('');
  }

  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

export function renderProtoStyleEntryCss({
  themeImport,
  tokensImport,
}: {
  themeImport: string;
  tokensImport: string;
}): string {
  return [
    '/* This file is auto-generated by @proto.ui/cli. */',
    '/* Do not edit by hand. */',
    '',
    `@import '${themeImport}';`,
    `@import '${tokensImport}';`,
    '',
  ].join('\n');
}

export function renderPrefixedThemeCss(input: string): string {
  const variableNames = new Set<string>();
  input.replace(/--([a-z0-9-]+)\s*:/g, (_match, name: string) => {
    variableNames.add(name);
    return '';
  });

  let css = input.replace(/--([a-z0-9-]+)\s*:/g, '--pui-$1:');
  css = css.replace(/var\(--([a-z0-9-]+)\)/g, (match, name: string) => {
    return variableNames.has(name) ? `var(--pui-${name})` : match;
  });
  css = css.replace(/var\(--color-blue-300\)/g, '#93c5fd');
  css = css.replace(/var\(--color-blue-500\)/g, '#3b82f6');
  css = css.replace(/var\(--color-blue-600\)/g, '#2563eb');
  css = css.replace(/var\(--color-blue-700\)/g, '#1d4ed8');
  css = css.replace(/var\(--color-blue-800\)/g, '#1e40af');
  css = css.replace(
    /(--pui-radius:\s*[^;]+;)/,
    [
      '$1',
      '    --pui-radius-xl: calc(var(--pui-radius) + 4px);',
      '    --pui-radius-lg: var(--pui-radius);',
      '    --pui-radius-md: calc(var(--pui-radius) - 2px);',
      '    --pui-radius-sm: calc(var(--pui-radius) - 4px);',
    ].join('\n')
  );

  return `${css.trimEnd()}\n`;
}

function renderTokenRule(token: string): CssRule | null {
  const parts = splitVariants(token);
  const utility = parts[parts.length - 1] ?? token;
  const css = renderUtility(utility);
  if (!css) return null;
  return { token, css };
}

function renderUtility(utility: string): string[] | null {
  if (utility in staticUtilities) return staticUtilities[utility] ?? [];

  const spacingRule = renderSpacingUtility(utility);
  if (spacingRule) return spacingRule;

  const colorRule = renderColorUtility(utility);
  if (colorRule) return colorRule;

  const roundedRule = renderRoundedUtility(utility);
  if (roundedRule) return roundedRule;

  const transformRule = renderTransformUtility(utility);
  if (transformRule) return transformRule;

  return null;
}

function renderSpacingUtility(utility: string): string[] | null {
  const spacingMatch = utility.match(/^(gap|h|w|min-h|min-w|size|p|px|py|pl|pr|mt|top|left)-(.+)$/);
  if (!spacingMatch) return null;
  const [, kind, rawValue] = spacingMatch;
  const value = spacingValue(rawValue);
  if (!value) return null;

  if (kind === 'gap') return [`gap: ${value};`];
  if (kind === 'h') return [`height: ${value};`];
  if (kind === 'w') return [`width: ${value};`];
  if (kind === 'min-h') return [`min-height: ${value};`];
  if (kind === 'min-w') return [`min-width: ${value};`];
  if (kind === 'size') return [`width: ${value};`, `height: ${value};`];
  if (kind === 'p') return [`padding: ${value};`];
  if (kind === 'px') return [`padding-inline: ${value};`];
  if (kind === 'py') return [`padding-block: ${value};`];
  if (kind === 'pl') return [`padding-left: ${value};`];
  if (kind === 'pr') return [`padding-right: ${value};`];
  if (kind === 'mt') return [`margin-top: ${value};`];
  if (kind === 'top') return [`top: ${value};`];
  if (kind === 'left') return [`left: ${value};`];
  return null;
}

function renderColorUtility(utility: string): string[] | null {
  if (utility === 'bg-black/80') return ['background-color: rgb(0 0 0 / 0.8);'];

  const colorMatch = utility.match(/^(bg|text|border|ring|ring-offset)-([a-z-]+)(?:\/(\d+))?$/);
  if (!colorMatch) return null;
  const [, kind, name, opacity] = colorMatch;
  if (!colorVars.has(name)) return null;
  const color = colorValue(name, opacity);

  if (kind === 'bg') return [`background-color: ${color};`];
  if (kind === 'text') return [`color: ${color};`];
  if (kind === 'border') return [`border-color: ${color};`];
  if (kind === 'ring') return [`--pui-ring-color: ${color};`, ringShadow()];
  if (kind === 'ring-offset') return [`--pui-ring-offset-color: ${color};`];
  return null;
}

function renderRoundedUtility(utility: string): string[] | null {
  if (utility === 'rounded-full') return ['border-radius: 9999px;'];
  if (utility === 'rounded-xl') return ['border-radius: var(--pui-radius-xl);'];
  if (utility === 'rounded-lg') return ['border-radius: var(--pui-radius-lg);'];
  if (utility === 'rounded-md') return ['border-radius: var(--pui-radius-md);'];
  if (utility === 'rounded-[min(var(--radius-md),12px)]') {
    return ['border-radius: min(var(--pui-radius-md), 12px);'];
  }
  return null;
}

function renderTransformUtility(utility: string): string[] | null {
  if (utility === '-translate-x-1/2') return ['--pui-translate-x: -50%;', transformValue()];
  if (utility === '-translate-y-1/2') return ['--pui-translate-y: -50%;', transformValue()];
  if (utility === 'translate-x-0') return ['--pui-translate-x: 0px;', transformValue()];
  if (utility === 'translate-y-px') return ['--pui-translate-y: 1px;', transformValue()];

  const scaleMatch = utility.match(/^scale-\[(.+)\]$/);
  if (scaleMatch)
    return [
      `--pui-scale-x: ${scaleMatch[1]};`,
      `--pui-scale-y: ${scaleMatch[1]};`,
      transformValue(),
    ];

  return null;
}

function buildSelectors(token: string): string[] {
  const parts = splitVariants(token);
  const variants = parts.slice(0, -1);
  let selectors = [`:where([${PUI_STYLE_ATTR}~="${escapeCssString(token)}"])`];
  let dark = false;

  for (const variant of variants) {
    if (variant === 'dark') {
      dark = true;
      continue;
    }
    selectors = selectors.flatMap((selector) => applyVariant(selector, variant));
  }

  if (dark) {
    selectors = selectors.flatMap((selector) => [
      `:where(.dark) ${selector}`,
      `:where(.dark)${selector}`,
      `:where([data-theme='dark']) ${selector}`,
      `:where([data-theme='dark'])${selector}`,
    ]);
  }

  return selectors;
}

function applyVariant(selector: string, variant: string): string[] {
  if (variant === 'hover') return [`${selector}:hover`];
  if (variant === 'active') return [`${selector}:active`];
  if (variant === 'disabled') return [`${selector}:disabled`];
  if (variant === 'focus-visible') return [`${selector}:focus-visible`];

  if (variant.startsWith('aria-')) {
    const name = variant.slice('aria-'.length);
    return [`${selector}[aria-${name}='true']`];
  }

  const dataMatch = variant.match(/^data-\[(.+)\]$/);
  if (dataMatch) {
    const body = dataMatch[1] ?? '';
    const eq = body.indexOf('=');
    if (eq >= 0) {
      const name = body.slice(0, eq);
      const value = body.slice(eq + 1);
      return [`${selector}[data-${name}='${escapeCssString(value)}']`];
    }
    return [`${selector}[data-${body}]`];
  }

  return [selector];
}

function splitVariants(token: string): string[] {
  const parts: string[] = [];
  let current = '';
  let depth = 0;

  for (const char of token) {
    if (char === '[') depth += 1;
    if (char === ']') depth = Math.max(0, depth - 1);
    if (char === ':' && depth === 0) {
      parts.push(current);
      current = '';
      continue;
    }
    current += char;
  }

  parts.push(current);
  return parts.filter(Boolean);
}

function spacingValue(raw: string): string | null {
  if (raw === 'full') return '100%';
  if (raw === '1/2') return '50%';
  if (raw.startsWith('[') && raw.endsWith(']')) return raw.slice(1, -1);
  return spacing[raw] ?? null;
}

function colorValue(name: string, opacity?: string): string {
  const base = `var(--pui-${name})`;
  if (!opacity) return base;
  return `color-mix(in oklab, ${base} ${Number(opacity)}%, transparent)`;
}

function ringShadow() {
  return [
    'box-shadow: var(--pui-ring-inset, ) 0 0 0 var(--pui-ring-width, 0px) var(--pui-ring-color, var(--pui-ring));',
  ].join('');
}

function transformValue() {
  return [
    'transform: translate(var(--pui-translate-x, 0), var(--pui-translate-y, 0)) scale(var(--pui-scale-x, 1), var(--pui-scale-y, 1));',
  ].join('');
}

function escapeCssString(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}
